### ISSUE TITLE
Unable to run the tool

### ISSUE THREAD

**Issue by yuekang0629** [TradeRev/angular-swaggerific#6]
Hi, 

I got "TypeError: Cannot read property 'addPet' of undefined" when running this tool. I attached my code below. The pet.json file is copy&paste from your swagger JSON sample in http://traderev.github.io/angular-swaggerific/. 

Also, If I use <script src="bower_components/angular-simple-sprite/angular-swaggerific.min.js"></script> as suggested in your documentaion, I got the error "TypeError: AngularSwaggerific is not a function". But if I change to angular-swaggerific.js I don't see that error any more (but I got the "TypeError: Cannot read property 'addPet' of undefined" error mentioned above.

Could you give any advice?

``` html
<script src="angular/angular.js"></script>
<script src="angular-swaggerific/dist/angular-swaggerific.js"></script>
<div ng-app="myApp" ng-controller="petCtrl">
<script>
var app = angular.module('myApp', ['angular-swaggerific',]);
app.controller('petCtrl', function($scope,$log, $window, AngularSwaggerific) {
var mySwaggerAPI = new AngularSwaggerific('pet.json');

    mySwaggerAPI.pets.addPet({"id": 1})
    .then(function(data) {
        $log.log("Success! " + data);
        console.log("success");
    }, function(err) {
        $log.log("Error! " + err);
    });
});
</script>
```

**Comment by spivey** [comment]
I have the same issue.

**Comment by tusharghate** [comment]
Hi @yuekang0629,

Sorry for the late reply. The reason why you are seeing that error is because the constructor needs to be passed the raw JSON, not the filename. 

So instead of: 

`var mySwaggerAPI = new AngularSwaggerific('pet.json');`

You should have:

`var swaggerJson = '{"pets": { "addPet:" {}}}';`
`var mySwaggerAPI = new AngularSwaggerific(swaggerJson);`

The actual JSON for your Swagger API can be generated at [http://editor.swagger.io](http://editor.swagger.io). Just paste your YAML code into the generator, and then click on File > Download as JSON. Store this JSON on the $window or in a Service, and then use it to initialize AngularSwaggerific. 

Hope that helps!

Thanks,
Tushar
